### PR TITLE
support for product attributes with terms

### PR DESCRIPTION
**Pull request by mhadaily**
Hi, 
One of the issues that I faced today was to get all attributes terms which are not supported at the moment in the plugin. 

I have just added it so terms can also appear in the query. 

Thanks, 
Majid

### CODE REVIEW

**Review by pasdo501 — APPROVED** [review]
Looks good!

**Comment by pasdo501** [comment]
Thank you very much for that contribution! Will put the new version up shortly.

**Comment by mhadaily** [comment]
fantastic, let me know so I can update our codebase again pointing to your package. 

thank you for maintaining this package.

**Comment by pasdo501** [comment]
It's updated now!


-------- Original message --------

**Pull request merged**
